import { UserButton, useUser } from "@clerk/nextjs";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Head from "next/head";

export default function Home() {
  const router = useRouter();
  const { isSignedIn, isLoaded } = useUser();

  useEffect(() => {
    // If the user is not signed in, redirect to the login page
    if (!isSignedIn && isLoaded) {
      router.replace("/auth/login").catch((err) => {
        console.error("Failed to redirect:", err);
      });
    }
  }, [isSignedIn, isLoaded, router]);

  // If not signed in, return null to prevent a flash of unauthorized content
  if (!isSignedIn) return null;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="h-screen">
          <UserButton afterSignOutUrl="/auth/login" />
          <h1>Main Content</h1>
        </div>
      </main>
    </>
  );
}
